Repository eduardconstantin/Crypto-Rankings, pull requests merged in 2022-10, with the labels that each got.

#9 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest

#8 Added github starts to homepage
  src/App.js
  src/index.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 Added favicon and title
  public/favicon.ico
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 Feature:Change cards position [fixes #10]
  package-lock.json
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Create CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation, good first issue, hacktoberfest

#14 feat: add table that displays top 100
  src/App.js
  src/components/Table.jsx
  src/index.css
Labels: enhancement, hacktoberfest-accepted
